version: '3.2'

services:
    percona:
        container_name: percona
        ports:
            - "13306:3306"
        volumes:
            - ./var/lib/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress_user
            MYSQL_PASSWORD: 12345
        image: percona:5.7
    wordpress:
        image: wordpress:latest
        container_name: wordpress
        ports:
            - "80:80"
        environment:
            WORDPRESS_DB_HOST: percona:3306
            WORDPRESS_DB_USER: wordpress_user
            WORDPRESS_DB_PASSWORD: 12345
        depends_on:
            - percona
